brew "stow"
brew "tmux"
brew "neovim"
brew "fzf"
brew "fd"
brew "eza"
brew "bat"
brew "git-delta"
brew "starship"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "ripgrep"

cask "alacritty", args: { no_quarantine: true }
cask "font-inconsolata-nerd-font"
